### PR TITLE
3 create react app setup

### PR DESCRIPTION
**Pull request by joshuasoave**
Setup some basic HTML, CSS, and React App Components to give the page a basic layout and styling. Will need further edits.

### CODE REVIEW

**Comment by buddhablake** [comment]
Looks great to me, the only thing I would change is the to get rid of the cobra-client folder and just move everything inside up to the root.

**Review by peterb0yd — CHANGES_REQUESTED** [review]
@joshuasoave please remove the node_modules folder from git and add a .gitignore file

**Comment by joshuasoave** [comment]
sorry, I forgot to add the gitignore file. It is there now and the node modules have been removed

**Comment by joshuasoave** [comment]
Had a call with Blake today and am going to refactor the class components into functional components

**Pull request closed without merging**
